### ISSUE TITLE
Adjust demo to use Fix XR Body crouching and climbing

### ISSUE THREAD

**Issue by fire** [Malcolmnixon/GodotXRVmcTracker#4]
https://github.com/godotengine/godot/pull/89103

**Comment by Malcolmnixon** [comment]
The body crouching and climbing change was to Godot and should be available for general use with the Godot 4.3dev5 release.

**Comment by fire** [comment]
So nothing to do?

**Comment by Malcolmnixon** [comment]
Shouldn't be. I did some basic checks standing on things and verifying I was able to actually move the avatar up. You may want to confirm with a build of Godot master, or Godot 4.3-dev5 when it comes out, and see if you can find any positioning issues.
